### ISSUE TITLE
Support for liquid templating

### ISSUE THREAD

**Issue by nottrobin** [marijnh/heckle#11]
Are there any plans to support liquid templating? divillysausages seems to have [got it to work](https://divillysausages.com/2016/01/24/leaving-jekyll-behind/).

**Comment by marijnh** [comment]
Not really. That link seems to talk about a fork -- maybe you could use that.

**Comment by nottrobin** [comment]
Yep I could try. I'm also interested in having a Jekyll clone written in NodeJS, as our projects usually have Node as their key dependency, and adding Ruby as well just makes things messy.

But Jekyll is by far the most common static site generator, not to mention the only one supported by GitHub pages. So I'd ideally like a tool to build our existing Jekyll sites as they are, but based on NodeJS.

I'm happy to spend some time collaborating on a tool to do this, but I'm trying to work out which one is best. None of the ones I've found so far seem to have much of a community around them (and the Jekyll peeps themselves [don't seem interested](https://github.com/jekyll/jekyll/issues/3986)). So if you would rather not support Liquid then maybe I should just fork either Heckle or JekyllJS and start working on it as a separate project?

**Comment by marijnh** [comment]
I'm busy with other projects, and am only using this for rendering a simple blog, so yeah, I'd prefer a fork if you're going to do serious work.

**Comment by nottrobin** [comment]
Cool. Thanks for taking the time to explain that. If I do get around to creating a decent fork, I'll try to find the time to update here for posterity.
