### ISSUE TITLE
no support for .markdown files

### ISSUE THREAD

**Issue by colbyrussell** [marijnh/heckle#5]
heckle supports `.md` for markdown files, but not `.markdown`.  I always use the latter, because the `.md` extension is ambiguous.  (Stock Vim on latest Ubuntu LTS recognizes `.markdown` correctly, but interprets `.md` as module2, for example.)

This is fixed on [my extraproc branch](https://gitlab.com/crussell/heckle/commits/extraproc).  It doesn't look like GitHub pull requests have (even second class) support for non-GitHub-hosted merges, so this issue will have to do I guess.

**Comment by marijnh** [comment]
Fixed via #6
