### ISSUE TITLE
no layout support for non-markdown files

### ISSUE THREAD

**Issue by colbyrussell** [marijnh/heckle#6]
I started to migrate a basic, stagnant, sparse jekyll blog to heckle, but some pages were YAML+HTML instead of YAML+markdown.  Current heckle doesn't know anything about the former; it expects that `.html` will just be HTML.

This is fixed on [my extraproc branch](https://gitlab.com/crussell/heckle/commits/extraproc).

**Comment by colbyrussell** [comment]
(Hopefully the name changes in commit [220c26b](https://gitlab.com/crussell/heckle/commit/220c26b94faedc659890cc05ea78bd50c91f1f18) come off as sensible instead of "jerky" or mistaken for [amateurishness](http://tirania.org/blog/archive/2010/Dec-31.html).)

**Comment by marijnh** [comment]
Looks good. I've merged your branch (squashing the last two commits together).
