### ISSUE TITLE
.link files should be generated

### ISSUE THREAD

**Issue by codinggirl** [marijnh/heckle#8]
In my opinion, .link files are used for old posts renaming, or link into the third part website, maybe we should generate them in static files, and it would auto redirect to the target page.

In posts list, the .link files is a optional for display. If it links to third part web page, it should shows in posts list, but if it is a old post link, it should not appears in posts list. Maybe we should show out   this condition.

**Comment by marijnh** [comment]
> In my opinion, .link files are used for old posts renaming,

That may be, but that's not what I actually implemented them for. I implemented them to link to external URLs, so that's what they are good at.
